inputs5 = {
    "local" : {"username":"achotaliya@operasolutions.com","password":"P@ssw0rd"},
    "solution_name" : 'CVS-QA2',
    "s_name" : 'CVSQA2',
    "explorer" : "USE CASE EXPLORER",
    "datalayer_name" : "List Pull - Promo Targeting",
    "search" : "promo",
    "name_value1" : "testing_wf",
    "name_value2" : "promo_targeting",
    "fqn_value1" : "listpull.common.pop_segment.low_e_pop",
    "fqn_value2" : "listpull.common.sku_selection.ad_version_segment_sku_sigs",
    "fqn_value3" : "listpull.welcome.base_pop_QC",
    "fqn_value4" : "listpull.common.pop_segment.recent_pop",
    "fqn_value5" : "listpull.ob_dynamic.low_e_pop",
    "fqn_value6" : "listpull.listpull_reports.basket_builder",
    "fqn_value" : "listpull.promo_targeting.promo_targeting",
    "signal_name1" : "Front store total sales amount in past 12 months",
    "signal_name2" : "Segment number of the customer",
    'host_name' : "http://172.24.6.32:8098"
}
